### ISSUE TITLE
赞！

### ISSUE THREAD

**Issue by yanglilizhang** [finovy/finovy_ui_kit_app#1]
感谢作者优秀的项目，我运行当前项目的时候提示Error: The non-abstract class 'ZhCupertinoLocalizations' is missing implementations for these members是什么原因，我尝试了flutter:3.10.0和3.16.0均失败，怎么解决这个问题
![Screenshot_1](https://github.com/finovy/finovy_ui_kit_app/assets/42633135/d678a11d-5eee-4b8b-befe-23ccd3dc865d)

**Comment by finovy** [comment]
感谢反馈，经过排查是flutter SDK版本的问题，已经更新 @yanglilizhang

**Comment by yanglilizhang** [comment]
> 感谢反馈，经过排查是flutter SDK版本的问题，已经更新 @yanglilizhang

小米手机上还有这种问题
https://github.com/finovy/finovy_ui_kit_app/assets/42633135/982ee2bf-067c-4998-89bd-786c679e7409

**Comment by finovy** [comment]
已修复，应该没有这个问题了 @yanglilizhang

**Comment by yanglilizhang** [comment]
> 已修复，应该没有这个问题了 @yanglilizhang

收到谢谢
